register:
    path: /
    controller: App\Controller\RegistrationController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index


